name: ci

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: RSpec
    strategy:
      matrix:
        ruby: ['3.4', '4.0']
    timeout-minutes: 3
    env:
      BUNDLE_ONLY: ci
    steps:
      - uses: actions/checkout@v3
      - name: set ruby version
        run: |
          echo ruby_version=`cat .ruby-version` >> "$GITHUB_ENV"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run parallelized build
        run: bundle exec rake suite:all:parallel
#      - name: Upload coverage directory
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: coverage-report
#          path: coverage/
