name: ci

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: RSpec
    timeout-minutes: 3
    env:
      BUNDLE_ONLY: ci
    steps:
      - uses: actions/checkout@v3
      - name: set ruby version
        run: |
          echo ruby_version=`cat .ruby-version` >> "$GITHUB_ENV"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run parallelized build
        run: bundle exec rake suite:all:parallel
