name: ci

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: RSpec
    timeout-minutes: 3
    env:
      BUNDLE_ONLY: ci
    steps:
      - uses: actions/checkout@v3
      - name: set ruby version
        run: |
          echo ruby_version=`cat .ruby-version` >> "$GITHUB_ENV"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run root specs
        run: bundle exec rspec
      - name: Run command_connectors specs
        run: cd foobara/projects/command_connectors && bundle exec rspec
      - name: Verify 100% coverage
        run: bundle exec rake spec:coverage
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    timeout-minutes: 3
    env:
      BUNDLE_ONLY: ci
    steps:
      - uses: actions/checkout@v3
      - name: set ruby version
        run: |
          echo ruby_version=`cat .ruby-version` >> "$GITHUB_ENV"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
